apiVersion: v1
kind: Pod
metadata:
  name: secret-pod-demo
  # labels:
  #   app: nginx
spec:
  containers:
  - name: demo
    image: busybox
    command: ["sh", "-c", "The DB pass is $DB_PASS && sleep 3600"]
    env:
    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: password
